version: '2'
services:
 consul-server:
    hostname: consul-server
    build: ./consul-server/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "consul agent -data-dir=/tmp/consul -server -bootstrap-expect 3 -ui-dir /opt -client 0.0.0.0"
 consul-client-1:
    hostname: consul-client-1
    build: ./consul-client-1/
    ports:
      - "8400"
      - "8500"
      - "8600"
    command: "consul agent -data-dir=/tmp/consul -server -join consul-server"
 consul-client-2:
    hostname: consul-client-2
    build: ./consul-client-2/
    ports:
      - "8400"
      - "8500"
      - "8600"
    command: "consul agent -data-dir=/tmp/consul -server -join consul-server"
