version: '2'
services:
 consul-server:
    hostname: consul-server
    build: ./consul-server/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "consul agent -data-dir=/tmp/consul -server -bootstrap-expect 2 -ui-dir /opt"
 consul-client:
    hostname: consul-client
    build: ./consul-client/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "consul agent -data-dir=/tmp/consul -server -join consul-server"
